package com.aymankhattab.nateq.engine

import java.util.regex.Matcher
import java.util.regex.Pattern

/**
 * قواميس أسماء الإيموجي للنطق: خريطة كل كود نقطة Unicode إلى اسمٍ يُنطق
 * (عربي/إنجليزي). كل الإيموجي غير المدخلة هنا تُنطق بكلمة عامة ثابتة
 * (AR_FALLBACK / EN_FALLBACK) حتى لا يُحذف أي إيموجي بصمت.
 */
object EmojiNames {

    const val AR_FALLBACK = "إيموجي"
    const val EN_FALLBACK = "emoji"
    const val AR_FLAG_FALLBACK = "علم"
    const val EN_FLAG_FALLBACK = "flag"

    val AR: Map<Int, String> = emojiMap(
        0x1F600 to "وجه مبتسم",
        0x1F601 to "وجه ضاحك بعينين مبتسمتين",
        0x1F602 to "وجه يضحك بدموع",
        0x1F603 to "وجه ضاحك بعينين واسعتين",
        0x1F604 to "وجه ضاحك بعينين مبتسمتين",
        0x1F605 to "وجه ضاحك بعرق",
        0x1F606 to "وجه ضاحك بعينين مغمضتين",
        0x1F607 to "وجه مبتسم بهالة",
        0x1F608 to "وجه مبتسم بقرون",
        0x1F609 to "وجه يغمز",
        0x1F60A to "وجه مبتسم بعينين مبتسمتين",
        0x1F60B to "وجه يتذوق الطعام",
        0x1F60C to "وجه مرتاح",
        0x1F60D to "وجه معجب بالقلوب",
        0x1F60E to "وجه مبتسم بنظارات",
        0x1F60F to "وجه ماكر",
        0x1F610 to "وجه محايد",
        0x1F611 to "وجه بلا تعبير",
        0x1F612 to "وجه ساخط",
        0x1F613 to "وجه منكفئ بعرق",
        0x1F614 to "وجه مفكر بحزن",
        0x1F615 to "وجه محتار",
        0x1F617 to "وجه يقبّل",
        0x1F618 to "وجه يرسل قبلة",
        0x1F619 to "وجه يقبّل بعينين مبتسمتين",
        0x1F61A to "وجه يقبّل بعينين مغمضتين",
        0x1F61B to "وجه يخرج لسانه",
        0x1F61C to "وجه يغمز ويلعب",
        0x1F61D to "وجه يخرج لسانه بعينين مغمضتين",
        0x1F61E to "وجه خائب",
        0x1F61F to "وجه قلق",
        0x1F620 to "وجه غاضب",
        0x1F621 to "وجه متجهم غاضب",
        0x1F622 to "وجه يبكي",
        0x1F623 to "وجه متحمل",
        0x1F624 to "وجه ينفث غضباً",
        0x1F625 to "وجه حزين مستريح",
        0x1F626 to "وجه عابس بفم مفتوح",
        0x1F627 to "وجه متألم",
        0x1F628 to "وجه خائف",
        0x1F629 to "وجه منهك",
        0x1F62A to "وجه نعسان",
        0x1F62B to "وجه متعب",
        0x1F62C to "وجه متألم مبتسم",
        0x1F62D to "وجه يبكي بشدة",
        0x1F62E to "وجه مندهش",
        0x1F62F to "وجه مصدوم",
        0x1F630 to "وجه مذعور بعرق",
        0x1F631 to "وجه يصرخ خوفاً",
        0x1F632 to "وجه مصعوق",
        0x1F633 to "وجه مذهول",
        0x1F634 to "وجه نائم",
        0x1F635 to "وجه دوخان",
        0x1F636 to "وجه بلا فم",
        0x1F637 to "وجه مقنع",
        0x1F638 to "وجه قط ضاحك بعينين مبتسمتين",
        0x1F639 to "قط يضحك بدموع",
        0x1F63A to "قط مبتسم بفم مفتوح",
        0x1F63B to "قط معجب بالقلوب",
        0x1F63C to "قط بابتسامة ملتوية",
        0x1F63D to "قط يقبّل",
        0x1F63E to "قط غاضب",
        0x1F63F to "قط يبكي",
        0x1F640 to "قط منهك",
        0x1F641 to "وجه حزين قليلاً",
        0x1F642 to "وجه مبتسم قليلاً",
        0x1F643 to "وجه مقلوب",
        0x1F644 to "وجه يلف عينيه",
        0x1F910 to "وجه بفم مقفل",
        0x1F912 to "وجه مريض بميزان حرارة",
        0x1F913 to "وجه مثقف بنظارات",
        0x1F914 to "وجه مفكر",
        0x1F915 to "وجه مصاب بضمادة",
        0x1F916 to "وجه روبوت",
        0x1F917 to "وجه يحتضن",
        0x1F918 to "إشارة قرون المعدن",
        0x1F919 to "إشارة اتصل بي",
        0x1F91A to "ظهر اليد المرفوعة",
        0x1F91B to "قبضة لليسار",
        0x1F91C to "قبضة لليمين",
        0x1F91D to "مصافحة",
        0x1F91E to "أصابع متقاطعة",
        0x1F920 to "وجه راعي بقر",
        0x1F921 to "وجه مهرج",
        0x1F922 to "وجه يتقيأ",
        0x1F923 to "يضحك انفجاراً",
        0x1F924 to "وجه يسيل لعابه",
        0x1F925 to "وجه كاذب",
        0x1F926 to "راحة اليد على الجبهة",
        0x1F927 to "وجه يعطس",
        0x1F928 to "وجه بحاجب مرفوع",
        0x1F929 to "وجه مبهور",
        0x1F92A to "وجه مجنون",
        0x1F92B to "وجه يأمر بالسكوت",
        0x1F92C to "وجه غاضب برموز",
        0x1F92D to "وجه يضع يده على فمه",
        0x1F92E to "وجه يتقيأ",
        0x1F92F to "رأس منفجرة",
        0x1F930 to "امرأة حامل",
        0x1F931 to "أم ترضع",
        0x1F932 to "كفان مرفوعتان",
        0x1F933 to "صورة ذاتية",
        0x1F934 to "أمير",
        0x1F935 to "رجل يرتدي بدلة رسمية",
        0x1F936 to "المرأة سانتا",
        0x1F937 to "هز الكتفين",
        0x1F938 to "شخص يشقلب",
        0x1F939 to "شخص يشعوذ",
        0x1F93A to "مبارز بالسيوف",
        0x1F93C to "مصارعون",
        0x1F93D to "لاعب كرة الماء",
        0x1F93E to "لاعب كرة اليد",
        0x1F44F to "تصفيق",
        0x1F44D to "إبهام لأعلى",
        0x1F44E to "إبهام لأسفل",
        0x1F44C to "إشارة موافق",
        0x1F44B to "يد تلوّح",
        0x1F44A to "قبضة مرفوعة",
        0x1F448 to "إصبع يشير لليسار",
        0x1F449 to "إصبع يشير لليمين",
        0x1F4AA to "عضلة اليد",
        0x1F450 to "يدان مفتوحتان",
        0x1F440 to "عينان",
        0x1F441 to "عين",
        0x1F445 to "لسان",
        0x1F464 to "شخص",
        0x1F465 to "أشخاص",
        0x1F466 to "صبي",
        0x1F467 to "فتاة",
        0x1F468 to "رجل",
        0x1F469 to "امرأة",
        0x2764 to "قلب أحمر",
        0x1F493 to "قلب ينبض",
        0x1F494 to "قلب مكسور",
        0x1F495 to "قلبان",
        0x1F496 to "قلب متلألئ",
        0x1F497 to "قلب يكبر",
        0x1F498 to "قلب بسهم",
        0x1F499 to "قلب أزرق",
        0x1F49A to "قلب أخضر",
        0x1F49B to "قلب أصفر",
        0x1F49C to "قلب بنفسجي",
        0x1F49D to "قلب بشريط",
        0x1F49E to "قلوب متداخلة",
        0x1F49F to "زخرفة قلب",
        0x1F5A4 to "قلب أسود",
        0x1F388 to "بالون",
        0x1F389 to "قصاصات الاحتفال",
        0x1F38A to "كرة قصاصات",
        0x1F381 to "هدية مغلفة",
        0x1F382 to "كعكة عيد الميلاد",
        0x1F383 to "قرعة الهالوين",
        0x1F384 to "شجرة الميلاد",
        0x1F386 to "ألعاب نارية",
        0x1F525 to "نار",
        0x1F4A1 to "مصباح كهربائي",
        0x1F4A2 to "رمز الغضب",
        0x1F4A3 to "قنبلة",
        0x1F4A4 to "نائم يغطّ",
        0x1F4A5 to "تصادم",
        0x1F4A6 to "قطرات عرق",
        0x1F4A7 to "قطرة ماء",
        0x1F4A8 to "رمز السرعة",
        0x1F4A9 to "كومة براز",
        0x1F4AB to "نجمة الدوار",
        0x1F4AC to "فقاعة كلام",
        0x1F4AD to "فقاعة تفكير",
        0x1F4AF to "رمز مئة نقطة",
        0x1F4B0 to "كيس مال",
        0x1F4B3 to "بطاقة ائتمان",
        0x1F4B4 to "ورقة نقدية",
        0x1F4B5 to "ورقة نقدية يابانية",
        0x1F4B1 to "صرافة عملات",
        0x1F4B2 to "رمز الدولار السميك",
        0x1F4B9 to "رسم بياني صاعد",
        0x2600 to "شمس",
        0x2601 to "سحابة",
        0x2614 to "مظلة بالمطر",
        0x26A1 to "صاعقة كهربائية",
        0x2B50 to "نجمة",
        0x2728 to "تلألؤ",
        0x2744 to "ندفة ثلج",
        0x1F31F to "قمر مكتمل بوجه",
        0x1F31E to "شمس بوجه",
        0x1F31D to "بدر",
        0x1F308 to "قوس قزح",
        0x1F30D to "كرة أرضية",
        0x2705 to "علامة صح",
        0x2714 to "علامة صح",
        0x2716 to "إشارة خطأ",
        0x274C to "علامة خطأ",
        0x274E to "علامة خطأ مربعة",
        0x2753 to "علامة استفهام",
        0x2754 to "علامة استفهام بيضاء",
        0x2755 to "علامة تعجب بيضاء",
        0x2757 to "علامة تعجب",
        0x2B05 to "سهم لليسار",
        0x2B06 to "سهم لأعلى",
        0x2B07 to "سهم لأسفل",
        0x27A1 to "سهم لليمين",
        0x2B55 to "دائرة حمراء",
        0x26A0 to "تحذير",
        0x26D4 to "ممنوع الدخول",
        0x267F to "رمز الكرسي المتحرك",
        0x26BD to "كرة قدم",
        0x26BE to "كرة بيسبول",
        0x1F3C0 to "كرة سلة",
        0x1F3C8 to "كرة قدم أمريكية",
        0x1F3C9 to "كرة رغبي",
        0x1F3AE to "لعبة فيديو",
        0x1F3B1 to "بلياردو",
        0x1F3B8 to "نوتات موسيقية",
        0x1F3BC to "مقطوعة موسيقية",
        0x1F3A7 to "سماعة رأس",
        0x1F3B5 to "نوتة موسيقية",
        0x2708 to "طائرة",
        0x1F680 to "صاروخ",
        0x1F695 to "سيارة أجرة",
        0x1F697 to "سيارة",
        0x1F698 to "سيارة قادمة",
        0x1F699 to "شاحنة",
        0x1F6A5 to "إشارة مرور",
        0x1F6A7 to "أعمال بناء",
        0x1F6A8 to "سيارة شرطة",
        0x1F6B2 to "دراجة",
        0x1F6B6 to "شخص يمشي",
        0x1F34E to "تفاحة حمراء",
        0x1F34F to "تفاحة خضراء",
        0x1F35F to "بطاطس مقلية",
        0x1F354 to "هامبرغر",
        0x1F355 to "بيتزا",
        0x1F35D to "معكرونة",
        0x1F37A to "كوب بيرة",
        0x1F37B to "كؤوس بيرة",
        0x1F37C to "زجاجة رضاعة",
        0x1F370 to "كعكة بالفراولة",
        0x1F371 to "علبة غداء",
        0x1F372 to "طنجرة طعام",
        0x1F373 to "طبخ",
        0x1F374 to "شوكة وسكين",
        0x1F375 to "كوب شاي",
        0x1F376 to "كأس نبيذ",
        0x1F377 to "كأس كوكتيل",
        0x1F378 to "مشروب استوائي",
        0x1F37E to "كأسا نخب",
        0x1F37F to "فشار",
        0x1F344 to "فطر",
        0x1F345 to "طماطم",
        0x1F346 to "باذنجان",
        0x1F347 to "عنب",
        0x1F348 to "شمام",
        0x1F349 to "بطيخ",
        0x1F34A to "يوسفي",
        0x1F34B to "ليمون",
        0x1F34C to "موز",
        0x1F34D to "أناناس",
        0x1F352 to "كرز",
        0x1F42F to "وجه نمر",
        0x1F431 to "وجه قطة",
        0x1F436 to "وجه كلب",
        0x1F437 to "وجه خنزير",
        0x1F438 to "وجه ضفدع",
        0x1F439 to "وجه هامستر",
        0x1F43A to "وجه ذئب",
        0x1F43B to "وجه دب",
        0x1F43C to "وجه باندا",
        0x1F42D to "وجه فأر",
        0x1F42E to "وجه بقرة",
        0x1F430 to "وجه أرنب",
        0x1F432 to "وجه نمر",
        0x1F434 to "وجه حصان",
        0x1F435 to "وجه قرد",
        0x1F408 to "قطة",
        0x1F415 to "كلب",
        0x1F40D to "أفعى",
        0x1F40E to "حصان",
        0x1F418 to "فيل",
        0x1F419 to "أخطبوط",
        0x1F41B to "حشرة",
        0x1F41E to "خنفساء",
        0x1F40C to "حلزون",
        0x1F414 to "دجاجة",
        0x1F427 to "بطريق",
        0x1F426 to "طائر",
        0x1F42B to "جمل",
        0x1F42C to "جمل عربي",
        0x1F331 to "نبتة",
        0x1F332 to "شجرة",
        0x1F333 to "شجرة متساقطة الأوراق",
        0x1F334 to "شجرة نخيل",
        0x1F335 to "صبار",
        0x1F337 to "خزامى",
        0x1F338 to "زهرة الكرز",
        0x1F339 to "وردة",
        0x1F33A to "زهرة الخطمي",
        0x1F33B to "زهرة عباد الشمس",
        0x1F33E to "سنبل",
        0x1F340 to "برسيم رباعي",
        0x1F341 to "ورقة القيقب",
        0x1F342 to "ورقة متساقطة",
        0x1F343 to "ورقة تتطاير",
        0x1F45F to "حذاء رياضي",
        0x1F451 to "تاج",
        0x1F452 to "قبعة نسائية",
        0x1F453 to "نظارات",
        0x1F45E to "حذاء رجالي",
        0x1F484 to "أحمر الشفاه",
        0x1F485 to "طلاء أظافر",
        0x1F486 to "مساج الوجه",
        0x1F487 to "قصة شعر"
    )

    val AR_COUNTRY: Map<String, String> = countryMap(
        "EG" to "مصر",
        "SA" to "السعودية",
        "AE" to "الإمارات",
        "QA" to "قطر",
        "KW" to "الكويت",
        "BH" to "البحرين",
        "OM" to "عمان",
        "JO" to "الأردن",
        "LB" to "لبنان",
        "SY" to "سوريا",
        "IQ" to "العراق",
        "YE" to "اليمن",
        "PS" to "فلسطين",
        "TN" to "تونس",
        "DZ" to "الجزائر",
        "MA" to "المغرب",
        "LY" to "ليبيا",
        "SD" to "السودان",
        "US" to "أمريكا",
        "GB" to "بريطانيا",
        "FR" to "فرنسا",
        "DE" to "ألمانيا",
        "CA" to "كندا",
        "TR" to "تركيا",
        "IN" to "الهند",
        "PK" to "باكستان",
        "CN" to "الصين",
        "JP" to "اليابان",
        "KR" to "كوريا الجنوبية",
        "RU" to "روسيا",
        "AU" to "أستراليا",
        "BR" to "البرازيل",
        "AR" to "الأرجنتين",
        "ES" to "إسبانيا",
        "IT" to "إيطاليا",
        "NL" to "هولندا",
        "SE" to "السويد",
        "NO" to "النرويج",
        "GR" to "اليونان",
        "CH" to "سويسرا",
        "AT" to "النمسا",
        "BE" to "بلجيكا",
        "IL" to "إسرائيل",
        "IR" to "إيران",
        "AF" to "أفغانستان",
        "BD" to "بنغلاديش",
        "NP" to "نيبال",
        "MY" to "ماليزيا",
        "TH" to "تايلاند",
        "PH" to "الفلبين",
        "MX" to "المكسيك",
        "ZA" to "جنوب أفريقيا",
        "NG" to "نيجيريا",
        "ET" to "إثيوبيا",
        "KE" to "كينيا",
        "NZ" to "نيوزيلندا"
    )

    val EN: Map<Int, String> = emojiMap(
        0x1F600 to "beaming face",
        0x1F601 to "grinning face with smiling eyes",
        0x1F602 to "face with tears of joy",
        0x1F603 to "grinning face with big eyes",
        0x1F604 to "grinning face with smiling eyes",
        0x1F605 to "grinning face with sweat",
        0x1F606 to "grinning squinting face",
        0x1F607 to "smiling face with halo",
        0x1F608 to "smiling face with horns",
        0x1F609 to "winking face",
        0x1F60A to "smiling face with smiling eyes",
        0x1F60B to "face savoring food",
        0x1F60C to "relieved face",
        0x1F60D to "smiling face with heart-eyes",
        0x1F60E to "smiling face with sunglasses",
        0x1F60F to "smirking face",
        0x1F610 to "neutral face",
        0x1F611 to "expressionless face",
        0x1F612 to "unamused face",
        0x1F613 to "downcast face with sweat",
        0x1F614 to "pensive face",
        0x1F615 to "confused face",
        0x1F617 to "kissing face",
        0x1F618 to "face blowing a kiss",
        0x1F619 to "kissing face with smiling eyes",
        0x1F61A to "kissing face with closed eyes",
        0x1F61B to "face with tongue",
        0x1F61C to "winking face with tongue",
        0x1F61D to "squinting face with tongue",
        0x1F61E to "disappointed face",
        0x1F61F to "worried face",
        0x1F620 to "angry face",
        0x1F621 to "pouting face",
        0x1F622 to "crying face",
        0x1F623 to "persevering face",
        0x1F624 to "face with steam from nose",
        0x1F625 to "sad but relieved face",
        0x1F626 to "frowning face with open mouth",
        0x1F627 to "anguished face",
        0x1F628 to "fearful face",
        0x1F629 to "weary face",
        0x1F62A to "sleepy face",
        0x1F62B to "tired face",
        0x1F62C to "grimacing face",
        0x1F62D to "loudly crying face",
        0x1F62E to "face with open mouth",
        0x1F62F to "hushed face",
        0x1F630 to "anxious face with sweat",
        0x1F631 to "face screaming in fear",
        0x1F632 to "astonished face",
        0x1F633 to "flushed face",
        0x1F634 to "sleeping face",
        0x1F635 to "dizzy face",
        0x1F636 to "face without mouth",
        0x1F637 to "face with medical mask",
        0x1F638 to "grinning cat with smiling eyes",
        0x1F639 to "cat with tears of joy",
        0x1F63A to "smiling cat with open mouth",
        0x1F63B to "heart-eyes cat",
        0x1F63C to "cat with wry smile",
        0x1F63D to "kissing cat",
        0x1F63E to "pouting cat",
        0x1F63F to "crying cat",
        0x1F640 to "weary cat",
        0x1F641 to "slightly frowning face",
        0x1F642 to "slightly smiling face",
        0x1F643 to "upside-down face",
        0x1F644 to "face with rolling eyes",
        0x1F910 to "zipper-mouth face",
        0x1F912 to "face with thermometer",
        0x1F913 to "nerd face",
        0x1F914 to "thinking face",
        0x1F915 to "face with head-bandage",
        0x1F916 to "robot face",
        0x1F917 to "hugging face",
        0x1F918 to "sign of the horns",
        0x1F919 to "call-me hand",
        0x1F91A to "raised back of hand",
        0x1F91B to "left-facing fist",
        0x1F91C to "right-facing fist",
        0x1F91D to "handshake",
        0x1F91E to "crossed fingers",
        0x1F920 to "cowboy hat face",
        0x1F921 to "clown face",
        0x1F922 to "nauseated face",
        0x1F923 to "rolling on the floor laughing",
        0x1F924 to "drooling face",
        0x1F925 to "lying face",
        0x1F926 to "face palm",
        0x1F927 to "sneezing face",
        0x1F928 to "face with raised eyebrow",
        0x1F929 to "star-struck",
        0x1F92A to "zany face",
        0x1F92B to "shushing face",
        0x1F92C to "face with symbols on mouth",
        0x1F92D to "face with hand over mouth",
        0x1F92E to "face vomiting",
        0x1F92F to "exploding head",
        0x1F930 to "pregnant woman",
        0x1F931 to "breast-feeding",
        0x1F932 to "palms up together",
        0x1F933 to "selfie",
        0x1F934 to "prince",
        0x1F935 to "person in tuxedo",
        0x1F936 to "Mrs. Claus",
        0x1F937 to "shrug",
        0x1F938 to "person cartwheeling",
        0x1F939 to "juggling",
        0x1F93A to "fencing",
        0x1F93C to "people wrestling",
        0x1F93D to "water polo",
        0x1F93E to "handball",
        0x1F44F to "clapping hands",
        0x1F44D to "thumbs up",
        0x1F44E to "thumbs down",
        0x1F44C to "OK hand",
        0x1F44B to "waving hand",
        0x1F44A to "raised fist",
        0x1F448 to "backhand index pointing left",
        0x1F449 to "backhand index pointing right",
        0x1F4AA to "flexed biceps",
        0x1F450 to "open hands",
        0x1F440 to "eyes",
        0x1F441 to "eye",
        0x1F445 to "tongue",
        0x1F464 to "person",
        0x1F465 to "people",
        0x1F466 to "boy",
        0x1F467 to "girl",
        0x1F468 to "man",
        0x1F469 to "woman",
        0x2764 to "red heart",
        0x1F493 to "beating heart",
        0x1F494 to "broken heart",
        0x1F495 to "two hearts",
        0x1F496 to "sparkling heart",
        0x1F497 to "growing heart",
        0x1F498 to "heart with arrow",
        0x1F499 to "blue heart",
        0x1F49A to "green heart",
        0x1F49B to "yellow heart",
        0x1F49C to "purple heart",
        0x1F49D to "heart with ribbon",
        0x1F49E to "revolving hearts",
        0x1F49F to "heart decoration",
        0x1F5A4 to "black heart",
        0x1F388 to "balloon",
        0x1F389 to "party popper",
        0x1F38A to "confetti ball",
        0x1F381 to "wrapped gift",
        0x1F382 to "birthday cake",
        0x1F383 to "jack-o-lantern",
        0x1F384 to "Christmas tree",
        0x1F386 to "fireworks",
        0x1F525 to "fire",
        0x1F4A1 to "electric light bulb",
        0x1F4A2 to "anger symbol",
        0x1F4A3 to "bomb",
        0x1F4A4 to "sleeping snore",
        0x1F4A5 to "collision",
        0x1F4A6 to "sweat droplets",
        0x1F4A7 to "droplet",
        0x1F4A8 to "dash symbol",
        0x1F4A9 to "pile of poo",
        0x1F4AB to "dizzy symbol",
        0x1F4AC to "speech balloon",
        0x1F4AD to "thought balloon",
        0x1F4AF to "hundred points",
        0x1F4B0 to "money bag",
        0x1F4B3 to "credit card",
        0x1F4B4 to "dollar banknote",
        0x1F4B5 to "yen banknote",
        0x1F4B1 to "currency exchange",
        0x1F4B2 to "heavy dollar sign",
        0x1F4B9 to "increasing chart",
        0x2600 to "sun",
        0x2601 to "cloud",
        0x2614 to "umbrella with rain drops",
        0x26A1 to "high voltage",
        0x2B50 to "star",
        0x2728 to "sparkles",
        0x2744 to "snowflake",
        0x1F31F to "full moon with face",
        0x1F31E to "sun with face",
        0x1F31D to "full moon",
        0x1F308 to "rainbow",
        0x1F30D to "globe",
        0x2705 to "check mark",
        0x2714 to "heavy check mark",
        0x2716 to "cross mark",
        0x274C to "cross mark",
        0x274E to "cross mark button",
        0x2753 to "question mark",
        0x2754 to "white question mark",
        0x2755 to "white exclamation mark",
        0x2757 to "exclamation mark",
        0x2B05 to "left arrow",
        0x2B06 to "up arrow",
        0x2B07 to "down arrow",
        0x27A1 to "right arrow",
        0x2B55 to "red circle",
        0x26A0 to "warning",
        0x26D4 to "no entry",
        0x267F to "wheelchair symbol",
        0x26BD to "soccer ball",
        0x26BE to "baseball",
        0x1F3C0 to "basketball",
        0x1F3C8 to "American football",
        0x1F3C9 to "rugby",
        0x1F3AE to "video game",
        0x1F3B1 to "pool",
        0x1F3B8 to "musical notes",
        0x1F3BC to "musical score",
        0x1F3A7 to "headphone",
        0x1F3B5 to "musical note",
        0x2708 to "airplane",
        0x1F680 to "rocket",
        0x1F695 to "taxi",
        0x1F697 to "car",
        0x1F698 to "oncoming automobile",
        0x1F699 to "truck",
        0x1F6A5 to "horizontal traffic light",
        0x1F6A7 to "construction",
        0x1F6A8 to "police car light",
        0x1F6B2 to "bicycle",
        0x1F6B6 to "pedestrian",
        0x1F34E to "red apple",
        0x1F34F to "green apple",
        0x1F35F to "french fries",
        0x1F354 to "hamburger",
        0x1F355 to "pizza",
        0x1F35D to "spaghetti",
        0x1F37A to "beer mug",
        0x1F37B to "clinking beer mugs",
        0x1F37C to "baby bottle",
        0x1F370 to "shortcake",
        0x1F371 to "bento box",
        0x1F372 to "pot of food",
        0x1F373 to "cooking",
        0x1F374 to "fork and knife",
        0x1F375 to "teacup",
        0x1F376 to "wine glass",
        0x1F377 to "cocktail glass",
        0x1F378 to "tropical drink",
        0x1F37E to "clinking glasses",
        0x1F37F to "popcorn",
        0x1F344 to "mushroom",
        0x1F345 to "tomato",
        0x1F346 to "eggplant",
        0x1F347 to "grapes",
        0x1F348 to "melon",
        0x1F349 to "watermelon",
        0x1F34A to "tangerine",
        0x1F34B to "lemon",
        0x1F34C to "banana",
        0x1F34D to "pineapple",
        0x1F352 to "cherries",
        0x1F42F to "tiger face",
        0x1F431 to "cat face",
        0x1F436 to "dog face",
        0x1F437 to "pig face",
        0x1F438 to "frog face",
        0x1F439 to "hamster face",
        0x1F43A to "wolf face",
        0x1F43B to "bear face",
        0x1F43C to "panda face",
        0x1F42D to "mouse face",
        0x1F42E to "cow face",
        0x1F430 to "rabbit face",
        0x1F432 to "tiger face",
        0x1F434 to "horse face",
        0x1F435 to "monkey face",
        0x1F408 to "cat",
        0x1F415 to "dog",
        0x1F40D to "snake",
        0x1F40E to "horse",
        0x1F418 to "elephant",
        0x1F419 to "octopus",
        0x1F41B to "bug",
        0x1F41E to "lady beetle",
        0x1F40C to "snail",
        0x1F414 to "chicken",
        0x1F427 to "penguin",
        0x1F426 to "bird",
        0x1F42B to "camel",
        0x1F42C to "dromedary",
        0x1F331 to "seedling",
        0x1F332 to "evergreen tree",
        0x1F333 to "deciduous tree",
        0x1F334 to "palm tree",
        0x1F335 to "cactus",
        0x1F337 to "tulip",
        0x1F338 to "cherry blossom",
        0x1F339 to "rose",
        0x1F33A to "hibiscus",
        0x1F33B to "sunflower",
        0x1F33E to "ear of rice",
        0x1F340 to "four leaf clover",
        0x1F341 to "maple leaf",
        0x1F342 to "fallen leaf",
        0x1F343 to "leaf fluttering in wind",
        0x1F45F to "running shoe",
        0x1F451 to "crown",
        0x1F452 to "woman's hat",
        0x1F453 to "glasses",
        0x1F45E to "man's shoe",
        0x1F484 to "lipstick",
        0x1F485 to "nail polish",
        0x1F486 to "face massage",
        0x1F487 to "haircut"
    )

    val EN_COUNTRY: Map<String, String> = countryMap(
        "EG" to "Egypt",
        "SA" to "Saudi Arabia",
        "AE" to "United Arab Emirates",
        "QA" to "Qatar",
        "KW" to "Kuwait",
        "BH" to "Bahrain",
        "OM" to "Oman",
        "JO" to "Jordan",
        "LB" to "Lebanon",
        "SY" to "Syria",
        "IQ" to "Iraq",
        "YE" to "Yemen",
        "PS" to "Palestine",
        "TN" to "Tunisia",
        "DZ" to "Algeria",
        "MA" to "Morocco",
        "LY" to "Libya",
        "SD" to "Sudan",
        "US" to "United States",
        "GB" to "United Kingdom",
        "FR" to "France",
        "DE" to "Germany",
        "CA" to "Canada",
        "TR" to "Turkey",
        "IN" to "India",
        "PK" to "Pakistan",
        "CN" to "China",
        "JP" to "Japan",
        "KR" to "South Korea",
        "RU" to "Russia",
        "AU" to "Australia",
        "BR" to "Brazil",
        "AR" to "Argentina",
        "ES" to "Spain",
        "IT" to "Italy",
        "NL" to "Netherlands",
        "SE" to "Sweden",
        "NO" to "Norway",
        "GR" to "Greece",
        "CH" to "Switzerland",
        "AT" to "Austria",
        "BE" to "Belgium",
        "IL" to "Israel",
        "IR" to "Iran",
        "AF" to "Afghanistan",
        "BD" to "Bangladesh",
        "NP" to "Nepal",
        "MY" to "Malaysia",
        "TH" to "Thailand",
        "PH" to "Philippines",
        "MX" to "Mexico",
        "ZA" to "South Africa",
        "NG" to "Nigeria",
        "ET" to "Ethiopia",
        "KE" to "Kenya",
        "NZ" to "New Zealand"
    )

    fun arName(cp: Int): String? = AR[cp]
    fun enName(cp: Int): String? = EN[cp]

    /** اسم الدولة للعلم (رمز من حرفين) في العربية أو الإنجليزية. */
    fun flagName(code: String, arabic: Boolean): String? =
        if (arabic) AR_COUNTRY[code] else EN_COUNTRY[code]

    /** رمز دولة (حرفان) من رمزي منطقة متجاورين (🇪🇬 → "EG"). */
    fun buildCountryCode(c1: Int, c2: Int): String {
        val a = (c1 - 0x1F1E6 + 'A'.code).toChar()
        val b = (c2 - 0x1F1E6 + 'A'.code).toChar()
        return "$a$b"
    }

    /** تمييز مؤشرات المناطق (🇦️..🇿️): تُقرن مثنىً لتكوين أعلام. */
    fun isRegionalIndicator(cp: Int): Boolean = cp in 0x1F1E6..0x1F1FF

    /** تعديلات إيموجي تُسقط بصمت: ZWJ، ألوان البشرة، مؤشرات شكل النص. */
    fun isEmojiModifier(cp: Int): Boolean =
        cp == 0x200D || cp in 0xFE0E..0xFE0F || cp in 0x1F3FB..0x1F3FF

    /** كتل الإيموجي الصوريّة (بدون مؤشر الشكل FE0F الذي يُعالج كتعديل). */
    fun isEmojiBlockCp(cp: Int): Boolean =
        cp in 0x1F300..0x1FAFF || cp in 0x2600..0x27BF ||
        cp in 0x2B00..0x2BFF || cp in 0x1F000..0x1F1FF

    /** اسم نطق العلم كاملاً («علم السعودية»/«flag of Saudi Arabia») مع تراجعٍ عام. */
    fun flagReadingName(code: String, arabic: Boolean): String {
        val country = flagName(code, arabic)
        return if (country != null) {
            (if (arabic) "علم " else "flag of ") + country
        } else if (arabic) {
            AR_FLAG_FALLBACK
        } else {
            EN_FLAG_FALLBACK
        }
    }

    /** رموز المشاعر النصية (ASCII/word-based) تُنطق بأسمائها قبل أي معالجة. */
    val ASCII_EMOTICONS: List<Triple<Pattern, String, String>> = listOf(
        Triple(
            Pattern.compile("(?<![\\p{L}\\d])</3(?![\\p{L}\\d])"),
            "قلب مكسور", "broken heart"
        ),
        Triple(
            Pattern.compile("(?<![\\p{L}\\d])<3(?![\\p{L}\\d])"),
            "قلب", "heart"
        ),
        Triple(
            Pattern.compile("(?<![\\p{L}\\d]):-'-(?![\\p{L}\\d])"),
            "بكاء", "crying"
        ),
        Triple(
            Pattern.compile("(?<![\\p{L}\\d]):'\\((?![\\p{L}\\d])"),
            "بكاء", "crying"
        ),
        Triple(
            Pattern.compile("(?<![\\p{L}\\d]):'(?![\\p{L}\\d])"),
            "بكاء", "crying"
        ),
        Triple(
            Pattern.compile("(?<![\\p{L}\\d]):-\\)(?![\\p{L}\\d])"),
            "ابتسامة", "smile"
        ),
        Triple(
            Pattern.compile("(?<![\\p{L}\\d]):\\)(?![\\p{L}\\d])"),
            "ابتسامة", "smile"
        ),
        Triple(
            Pattern.compile("(?<![\\p{L}\\d]);-\\)(?![\\p{L}\\d])"),
            "غمزة", "wink"
        ),
        Triple(
            Pattern.compile("(?<![\\p{L}\\d]);\\)(?![\\p{L}\\d])"),
            "غمزة", "wink"
        ),
        Triple(
            Pattern.compile("(?<![\\p{L}\\d]):-\\((?![\\p{L}\\d])"),
            "حزين", "sad"
        ),
        Triple(
            Pattern.compile("(?<![\\p{L}\\d]):\\((?![\\p{L}\\d])"),
            "حزين", "sad"
        ),
        Triple(
            Pattern.compile("(?<![\\p{L}\\d]):-D(?![\\p{L}\\d])"),
            "ضحك", "laughing"
        ),
        Triple(
            Pattern.compile("(?<![\\p{L}\\d]):D(?![\\p{L}\\d])"),
            "ضحك", "laughing"
        ),
        Triple(
            Pattern.compile("(?<![\\p{L}\\d])[xX][dD](?![\\p{L}\\d])"),
            "ضحك شديد", "laughing out loud"
        ),
        Triple(
            Pattern.compile("(?<![\\p{L}\\d]):-P(?![\\p{L}\\d])"),
            "يلعب", "playful"
        ),
        Triple(
            Pattern.compile("(?<![\\p{L}\\d]):P(?![\\p{L}\\d])"),
            "يلعب", "playful"
        ),
        Triple(
            Pattern.compile("(?<![\\p{L}\\d]):-\\*(?![\\p{L}\\d])"),
            "قبلة", "kiss"
        ),
        Triple(
            Pattern.compile("(?<![\\p{L}\\d]):\\*(?![\\p{L}\\d])"),
            "قبلة", "kiss"
        ),
        Triple(
            Pattern.compile("(?<![\\p{L}\\d]):-\\|(?![\\p{L}\\d])"),
            "محايد", "neutral"
        ),
        Triple(
            Pattern.compile("(?<![\\p{L}\\d]):\\|(?![\\p{L}\\d])"),
            "محايد", "neutral"
        ),
        Triple(
            Pattern.compile("(?<![\\p{L}\\d])\\^_\\^(?![\\p{L}\\d])"),
            "سعيد", "happy"
        )
    )

    /** استبدال رموز المشاعر النصية (":)", ":(", "<3"…) بأسمائها. */
    fun applyAsciiEmoticons(text: String, arabic: Boolean): String {
        var result = text
        for ((pattern, arWord, enWord) in ASCII_EMOTICONS) {
            result = pattern.matcher(result).replaceAll(
                Matcher.quoteReplacement(if (arabic) arWord else enWord)
            )
        }
        return result
    }

    private fun emojiMap(vararg pairs: Pair<Int, String>): Map<Int, String> =
        pairs.toMap()

    private fun countryMap(vararg pairs: Pair<String, String>): Map<String, String> =
        pairs.toMap()
}